const Router = require('@koa/router')
const addressBook = require('../controller/addressBook/addressBook')
const jwToken = require('../middleware/jwt')
const router = new Router()
router.post('/addressBook/addFriend', jwToken, addressBook.addFriend.bind(addressBook))
router.get('/addressBook/getFriend', jwToken, addressBook.getFriend.bind(addressBook))
router.get('/addressBook', jwToken, addressBook.getAddressBook.bind(addressBook))
module.exports = router.routes()
